export const DATE_PICKER_SHELL_MAX_WIDTH = 361;
export const DATE_PICKER_HORIZONTAL_INSET = 6;
export const DATE_PICKER_CALENDAR_MAX_WIDTH =
  DATE_PICKER_SHELL_MAX_WIDTH - DATE_PICKER_HORIZONTAL_INSET * 2;
