import { DAYFRAME_GLYPHS, type DayframeGlyph } from "./iconGlyphs";

// One icon language for web and iOS: every glyph lives in iconGlyphs.ts (generated by
// scripts/generate-icons.mjs). Activities store a Dayframe key, never a glyph name, so a
// Lucide rename cannot break stored data.

export const DAYFRAME_ACTIVITY_ICON_GROUPS = [
  { id: "work", label: "Work and study" },
  { id: "body", label: "Body and mind" },
  { id: "home", label: "Home and life" },
  { id: "people", label: "People" },
  { id: "travel", label: "Getting around" },
  { id: "free-time", label: "Free time" }
] as const;

export type DayframeActivityIconGroup = (typeof DAYFRAME_ACTIVITY_ICON_GROUPS)[number]["id"];

export const DAYFRAME_ACTIVITY_ICONS = [
  { key: "work", label: "Work", group: "work", glyph: "briefcase" },
  { key: "office", label: "Office", group: "work", glyph: "building-2" },
  { key: "admin", label: "Admin", group: "work", glyph: "inbox" },
  { key: "computer", label: "Computer", group: "work", glyph: "laptop" },
  { key: "code", label: "Code", group: "work", glyph: "code-xml" },
  { key: "writing", label: "Writing", group: "work", glyph: "pen-line" },
  { key: "learning", label: "Learning", group: "work", glyph: "book-open" },
  { key: "study", label: "Study", group: "work", glyph: "graduation-cap" },
  { key: "meeting", label: "Meeting", group: "work", glyph: "presentation" },
  { key: "calls", label: "Calls", group: "work", glyph: "phone" },
  { key: "email", label: "Email", group: "work", glyph: "mail" },
  { key: "languages", label: "Languages", group: "work", glyph: "languages" },
  { key: "gym", label: "Exercise", group: "body", glyph: "dumbbell" },
  { key: "walk", label: "Walk", group: "body", glyph: "footprints" },
  { key: "cycling", label: "Cycling", group: "body", glyph: "bike" },
  { key: "swimming", label: "Swimming", group: "body", glyph: "swimmer" },
  { key: "hiking", label: "Hiking", group: "body", glyph: "mountain" },
  { key: "health", label: "Health", group: "body", glyph: "heart-pulse" },
  { key: "sleep", label: "Sleep", group: "body", glyph: "moon" },
  { key: "mindfulness", label: "Mindfulness", group: "body", glyph: "flower-2" },
  { key: "focus", label: "Focus", group: "body", glyph: "brain" },
  { key: "medication", label: "Medication", group: "body", glyph: "pill" },
  { key: "doctor", label: "Doctor", group: "body", glyph: "stethoscope" },
  { key: "chores", label: "Chores", group: "home", glyph: "house" },
  { key: "meals", label: "Meals", group: "home", glyph: "utensils" },
  { key: "cooking", label: "Cooking", group: "home", glyph: "chef-hat" },
  { key: "errands", label: "Errands", group: "home", glyph: "shopping-bag" },
  { key: "groceries", label: "Groceries", group: "home", glyph: "shopping-cart" },
  { key: "personal", label: "Personal", group: "home", glyph: "user-round" },
  { key: "laundry", label: "Laundry", group: "home", glyph: "shirt" },
  { key: "garden", label: "Garden", group: "home", glyph: "sprout" },
  { key: "pets", label: "Pets", group: "home", glyph: "paw-print" },
  { key: "childcare", label: "Childcare", group: "home", glyph: "baby" },
  { key: "repairs", label: "Repairs", group: "home", glyph: "wrench" },
  { key: "finances", label: "Finances", group: "home", glyph: "wallet" },
  { key: "family", label: "Family", group: "people", glyph: "users" },
  { key: "social", label: "Social", group: "people", glyph: "message-circle" },
  { key: "partner", label: "Partner", group: "people", glyph: "heart" },
  { key: "events", label: "Events", group: "people", glyph: "party-popper" },
  { key: "volunteering", label: "Volunteering", group: "people", glyph: "hand-heart" },
  { key: "coffee", label: "Coffee", group: "people", glyph: "coffee" },
  { key: "commute", label: "Commute", group: "travel", glyph: "car" },
  { key: "bus", label: "Bus", group: "travel", glyph: "bus" },
  { key: "train", label: "Train", group: "travel", glyph: "train-front" },
  { key: "travel", label: "Travel", group: "travel", glyph: "plane" },
  { key: "boat", label: "Boat", group: "travel", glyph: "ship" },
  { key: "journey", label: "Journey", group: "travel", glyph: "route" },
  { key: "hobbies", label: "Hobbies", group: "free-time", glyph: "palette" },
  { key: "music", label: "Music", group: "free-time", glyph: "music" },
  { key: "instrument", label: "Instrument", group: "free-time", glyph: "guitar" },
  { key: "games", label: "Games", group: "free-time", glyph: "gamepad-2" },
  { key: "tv", label: "TV and film", group: "free-time", glyph: "tv" },
  { key: "photography", label: "Photography", group: "free-time", glyph: "camera" },
  { key: "outdoors", label: "Outdoors", group: "free-time", glyph: "tent" }
] as const satisfies ReadonlyArray<{
  key: string;
  label: string;
  group: DayframeActivityIconGroup;
  glyph: DayframeGlyph;
}>;

export type DayframeActivityIconKey = (typeof DAYFRAME_ACTIVITY_ICONS)[number]["key"];

/** Shown when an activity has no stored icon and its name suggests none. */
export const DAYFRAME_ACTIVITY_ICON_FALLBACK_GLYPH = "circle-dot" satisfies DayframeGlyph;

/** Glyphs for interface roles, so web and iOS draw the same shape for the same job. */
export const DAYFRAME_APP_ICONS = {
  today: "sun",
  calendar: "calendar-days",
  reports: "chart-column",
  review: "list-checks",
  library: "library",
  settings: "settings",
  places: "map-pin",
  account: "circle-user-round",
  start: "play",
  stop: "square",
  add: "plus",
  edit: "pencil",
  delete: "trash-2",
  undo: "undo-2",
  split: "scissors",
  merge: "git-merge",
  search: "search",
  more: "ellipsis",
  pin: "pin",
  tag: "tag",
  export: "download",
  close: "x",
  done: "check",
  next: "chevron-right",
  notification: "bell",
  sourceManual: "pencil",
  sourceLocation: "map-pin",
  sourceMotion: "person-standing",
  sourceHealth: "heart-pulse",
  sourceTimer: "timer",
  syncOffline: "cloud-off",
  syncSending: "refresh-cw",
  syncDone: "cloud-check",
  syncAttention: "cloud-alert"
} as const satisfies Record<string, DayframeGlyph>;

const ACTIVITY_ICON_BY_KEY = new Map<string, (typeof DAYFRAME_ACTIVITY_ICONS)[number]>(
  DAYFRAME_ACTIVITY_ICONS.map((icon) => [icon.key, icon])
);

export function isActivityIconKey(value: unknown): value is DayframeActivityIconKey {
  return typeof value === "string" && ACTIVITY_ICON_BY_KEY.has(value);
}

// First match wins, so specific phrases come before broad words ("Train to London" before
// "training", "Dog walk" before "walk", "Deep work" and "Client work" before "work").
const NAME_RULES: ReadonlyArray<readonly [RegExp, DayframeActivityIconKey]> = [
  [/\b(dog|cat|pets?|vet)\b/, "pets"],
  [/\b(deep work|focus)\b/, "focus"],
  [/\b(client|office)\b/, "office"],
  [/\bcode\b|\bcoding\b|\bprogramm|\bdevelop/, "code"],
  [/\b(gym|workouts?|exercise|training|lifting|run|running|jog|jogging|yoga|pilates|sports?|fitness)\b/, "gym"],
  [/\b(trains?|rail|tube|metro|subway)\b/, "train"],
  [/\b(walks?|walking|steps|stroll)\b/, "walk"],
  [/\b(swim|swimming|pool)\b/, "swimming"],
  [/\b(cycle|cycling|bike|biking|ride)\b/, "cycling"],
  [/\b(hike|hiking|climb|climbing)\b/, "hiking"],
  [/\b(sleep|nap|bed)\b/, "sleep"],
  [/\b(meditat\w*|mindful\w*|breath\w*)\b/, "mindfulness"],
  [/\b(doctor|dentist|gp|hospital|clinic|physio\w*)\b/, "doctor"],
  [/\b(medication|meds|pills?)\b/, "medication"],
  [/\b(health|therapy)\b/, "health"],
  [/\b(commut\w*)\b/, "commute"],
  [/\b(bus|coach)\b/, "bus"],
  [/\b(flights?|travel\w*|trips?|holidays?|vacation)\b/, "travel"],
  [/\b(ferry|boat|sailing)\b/, "boat"],
  [/\b(drive|driving|journey)\b/, "journey"],
  [/\b(grocer\w*|supermarket)\b/, "groceries"],
  [/\b(errands?|shopping|shops?)\b/, "errands"],
  [/\b(cook\w*|baking|bake)\b/, "cooking"],
  [/\b(brunch)\b.*\b(friends?)\b|\b(friends?|social\w*|party|pub|drinks)\b/, "social"],
  [/\b(meals?|lunch|dinner|breakfast|brunch|eating)\b/, "meals"],
  [/\b(coffee|caf[eé])\b/, "coffee"],
  [/\b(chores?|cleaning|tidy\w*|housework)\b/, "chores"],
  [/\b(laundry|ironing)\b/, "laundry"],
  [/\b(garden\w*)\b/, "garden"],
  [/\b(kids?|child\w*|baby|school run)\b/, "childcare"],
  [/\b(repairs?|diy|fix\w*)\b/, "repairs"],
  [/\b(budget\w*|financ\w*|bank\w*|tax\w*)\b/, "finances"],
  [/\b(guitar|piano|violin|drums?|instrument)\b/, "instrument"],
  [/\b(music|band|singing|choir)\b/, "music"],
  [/\b(games?|gaming)\b/, "games"],
  [/\b(tv|film|films|movies?|netflix)\b/, "tv"],
  [/\b(photo\w*)\b/, "photography"],
  [/\b(camping|outdoors?)\b/, "outdoors"],
  [/\b(hobby|hobbies|crafts?|painting|drawing)\b/, "hobbies"],
  [/\b(family|parents?|mum|mom|dad)\b/, "family"],
  [/\b(partner|date night|date)\b/, "partner"],
  [/\b(events?|wedding|birthday)\b/, "events"],
  [/\b(volunteer\w*|charity)\b/, "volunteering"],
  [/\b(meetings?|stand-?up|1:1)\b/, "meeting"],
  [/\b(calls?|phone)\b/, "calls"],
  [/\b(email|inbox)\b/, "email"],
  [/\b(admin|paperwork)\b/, "admin"],
  [/\b(writ\w*|blog\w*|journal\w*)\b/, "writing"],
  [/\b(spanish|french|german|italian|language\w*)\b/, "languages"],
  [/\b(study|studying|exams?|course|class|university|uni)\b/, "study"],
  [/\b(learn\w*|reading|read|books?|lessons?)\b/, "learning"],
  [/\b(computer|laptop)\b/, "computer"],
  [/\b(work|job)\b/, "work"],
  [/\b(personal|me time)\b/, "personal"]
];

/** The icon an activity gets from its name when nobody has picked one, or null. */
export function activityIconKeyForName(name: string): DayframeActivityIconKey | null {
  const normalized = name.trim().toLowerCase();
  if (!normalized) return null;
  for (const [pattern, key] of NAME_RULES) if (pattern.test(normalized)) return key;
  return null;
}

/** Stored key first, then the name, then the neutral dot. */
export function resolveActivityIcon({ icon, name }: { icon?: string | null; name?: string | null }): {
  key: DayframeActivityIconKey | null;
  glyph: DayframeGlyph;
} {
  const key = isActivityIconKey(icon) ? icon : name ? activityIconKeyForName(name) : null;
  return { key, glyph: key ? ACTIVITY_ICON_BY_KEY.get(key)!.glyph : DAYFRAME_ACTIVITY_ICON_FALLBACK_GLYPH };
}

export { DAYFRAME_GLYPHS, type DayframeGlyph };
