#!/usr/bin/env node
// Builds Dayframe's single icon geometry from lucide-react (ISC) plus Dayframe-drawn glyphs.
//
//   node scripts/generate-icons.mjs          write packages/shared/src/iconGlyphs.ts and the iOS tab-bar PNGs
//   node scripts/generate-icons.mjs --check  fail if either is stale (no rendering needed)
//
// Add a glyph by listing it in GLYPHS (or CUSTOM_GLYPHS) and re-running the script.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "apps/web/package.json"));
const lucideDir = join(dirname(require.resolve("lucide-react/package.json")), "dist/esm/icons");
const lucideVersion = JSON.parse(readFileSync(require.resolve("lucide-react/package.json"), "utf8")).version;
const registryPath = join(root, "packages/shared/src/iconGlyphs.ts");
const tabIconDir = join(root, "apps/mobile/assets/tab-icons");
const tabManifestPath = join(tabIconDir, "manifest.json");

// Lucide glyphs used anywhere in Dayframe: activities, navigation, actions, sources and sync state.
const GLYPHS = [
  "baby", "bell", "bike", "book-open", "brain", "briefcase", "building-2", "bus", "calendar-days", "camera",
  "car", "chart-column", "check", "chef-hat", "chevron-right", "circle-dot", "circle-user-round", "cloud-alert", "cloud-check",
  "cloud-off", "code-xml", "coffee", "download", "dumbbell", "ellipsis", "flower-2", "footprints", "gamepad-2",
  "git-merge", "graduation-cap", "guitar", "hand-heart", "heart", "heart-pulse", "house", "inbox", "languages",
  "laptop", "library", "list-checks", "mail", "map-pin", "message-circle", "moon", "mountain", "music", "palette",
  "party-popper", "paw-print", "pen-line", "pencil", "person-standing", "phone", "pill", "pin", "plane", "play",
  "plus", "presentation", "refresh-cw", "route", "scissors", "search", "settings", "ship", "shirt", "shopping-bag",
  "shopping-cart", "sprout", "square", "stethoscope", "sun", "tag", "tent", "timer", "train-front", "trash-2", "tv",
  "undo-2", "user-round", "users", "utensils", "wallet", "wrench", "x"
];

// Dayframe-drawn glyphs on Lucide's grid: 24 x 24, 2-point round strokes, outline only.
const CUSTOM_GLYPHS = {
  // Lucide has no swimmer. Head, reaching arm and body over the wave from Lucide's water icons.
  swimmer: [
    ["circle", { cx: "18", cy: "10", r: "1" }],
    ["path", { d: "M3 13.5c2.5-1 4.5-1.5 7-1l5-1.5" }],
    ["path", { d: "M8 12.5c0-3.5 2-6 5.5-6.5" }],
    ["path", { d: "M2 18q2.5 2 5 0t5 0 5 0 5 0" }]
  ]
};

// Native iOS tab bar icons, rendered as template images so UIKit tints them inside Liquid Glass.
const TAB_ICONS = { today: "sun", calendar: "calendar-days", reports: "chart-column" };
const TAB_POINTS = 26;

function lucideNodes(name) {
  const source = readFileSync(join(lucideDir, `${name}.mjs`), "utf8");
  const match = source.match(/const __iconNode = (\[[\s\S]*?\]);\s*\n\s*const /);
  if (!match) throw new Error(`lucide-react ${lucideVersion} has no icon node for "${name}" (renamed or an alias?)`);
  // The node literal is plain data: [["path", { d: "...", key: "..." }], ...].
  const nodes = Function(`"use strict"; return (${match[1]});`)();
  return nodes.map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
}

function buildGlyphs() {
  const glyphs = {};
  for (const name of [...GLYPHS].sort()) glyphs[name] = lucideNodes(name);
  for (const [name, nodes] of Object.entries(CUSTOM_GLYPHS)) {
    if (glyphs[name]) throw new Error(`Custom glyph "${name}" collides with a Lucide glyph`);
    glyphs[name] = nodes;
  }
  return Object.fromEntries(Object.entries(glyphs).sort(([a], [b]) => a.localeCompare(b)));
}

function registrySource(glyphs) {
  const body = Object.entries(glyphs)
    .map(([name, nodes]) => `  ${JSON.stringify(name)}: ${JSON.stringify(nodes)}`)
    .join(",\n");
  return `// Generated by scripts/generate-icons.mjs from lucide-react ${lucideVersion} (ISC licence,
// https://lucide.dev) plus Dayframe-drawn glyphs in the same geometry. Do not edit by hand.

export type DayframeGlyphElement = "circle" | "ellipse" | "line" | "path" | "polygon" | "polyline" | "rect";
export type DayframeGlyphNode = readonly [DayframeGlyphElement, Readonly<Record<string, string>>];

export const DAYFRAME_GLYPHS = {
${body}
} as const satisfies Record<string, readonly DayframeGlyphNode[]>;

export type DayframeGlyph = keyof typeof DAYFRAME_GLYPHS;
`;
}

function glyphSvg(nodes, { size, padding = 0, color = "#000000" }) {
  const box = 24 + padding * 2;
  const children = nodes
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([key, value]) => `${key}="${value}"`).join(" ")}/>`)
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="${-padding} ${-padding} ${box} ${box}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${children}</svg>`;
}

function tabManifest(glyphs) {
  const padding = (TAB_POINTS - 24) / 2;
  return Object.fromEntries(Object.entries(TAB_ICONS).map(([tab, glyph]) => [
    tab,
    {
      glyph,
      points: TAB_POINTS,
      svgSha256: createHash("sha256").update(glyphSvg(glyphs[glyph], { size: TAB_POINTS, padding })).digest("hex")
    }
  ]));
}

async function writeTabIcons(glyphs, manifest) {
  const sharp = require("sharp");
  mkdirSync(tabIconDir, { recursive: true });
  const padding = (TAB_POINTS - 24) / 2;
  for (const [tab, { glyph }] of Object.entries(manifest)) {
    for (const scale of [1, 2, 3]) {
      const size = TAB_POINTS * scale;
      const svg = glyphSvg(glyphs[glyph], { size, padding });
      const suffix = scale === 1 ? "" : `@${scale}x`;
      await sharp(Buffer.from(svg), { density: 72 * scale }).resize(size, size).png().toFile(join(tabIconDir, `${tab}${suffix}.png`));
    }
  }
  writeFileSync(tabManifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

const glyphs = buildGlyphs();
const registry = registrySource(glyphs);
const manifest = tabManifest(glyphs);

if (process.argv.includes("--check")) {
  const problems = [];
  if (!existsSync(registryPath) || readFileSync(registryPath, "utf8") !== registry) {
    problems.push("packages/shared/src/iconGlyphs.ts is stale");
  }
  if (!existsSync(tabManifestPath) || readFileSync(tabManifestPath, "utf8") !== `${JSON.stringify(manifest, null, 2)}\n`) {
    problems.push("apps/mobile/assets/tab-icons is stale");
  }
  for (const tab of Object.keys(TAB_ICONS)) {
    for (const suffix of ["", "@2x", "@3x"]) {
      if (!existsSync(join(tabIconDir, `${tab}${suffix}.png`))) problems.push(`missing tab icon ${tab}${suffix}.png`);
    }
  }
  if (problems.length) {
    console.error(`${problems.join("\n")}\nRun: node scripts/generate-icons.mjs`);
    process.exit(1);
  }
  console.log(`Icon registry and tab icons are current (${Object.keys(glyphs).length} glyphs).`);
} else {
  writeFileSync(registryPath, registry);
  await writeTabIcons(glyphs, manifest);
  console.log(`Wrote ${Object.keys(glyphs).length} glyphs and ${Object.keys(TAB_ICONS).length} tab icons.`);
}
